version: "2.1"
services:
  mysql:
    image: mysql:5.7
    volumes:    
     - ./mysql/data.sql:/docker-entrypoint-initdb.d/1-init.sql
    healthcheck:
      test: "mysql -uroot -ppass"
    environment:
      MYSQL_DATABASE: imdb
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
  webapp:
    build:
      context: ./      
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
    __BP_SH_DB_DSN: root:pass@tcp(mysql:3306)/shopify
  
