version: "2.1"
services:
  mysql:
    image: mysql:5.7
    volumes:    
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql -uroot -ppass"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=imdb
    ports:
      - "3307:3306"

  webapp:
    build:
      context: ./      
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - __MYSQL_DB_DSN=root:pass@tcp(mysql:3306)/imdb
  
